from enum import StrEnum


class MoneyUnit(StrEnum):
    PAISE = "paise"
    RUPEES = "rupees"


class Decision(StrEnum):
    AUTO_VERIFIED = "AUTO_VERIFIED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REFUSED = "REFUSED"
    UNRESOLVED = "UNRESOLVED"
    PENDING = "PENDING"
    SYSTEM_ERROR = "SYSTEM_ERROR"


class ExceptionType(StrEnum):
    SETTLEMENT_LEDGER_MISMATCH = "SETTLEMENT_LEDGER_MISMATCH"
    MISSING_BANK_CREDIT = "MISSING_BANK_CREDIT"
    UNEXPECTED_MULTIPLE_SETTLED_PAYMENTS = "UNEXPECTED_MULTIPLE_SETTLED_PAYMENTS"
    AMBIGUOUS_MATCH = "AMBIGUOUS_MATCH"
    PAISE_RUPEE_MISMATCH = "PAISE_RUPEE_MISMATCH"
    SETTLEMENT_BANK_AMOUNT_MISMATCH = "SETTLEMENT_BANK_AMOUNT_MISMATCH"
    BANK_TIMING_INCONSISTENCY = "BANK_TIMING_INCONSISTENCY"
    MANUAL_BANK_MATCH_REQUIRED = "MANUAL_BANK_MATCH_REQUIRED"
    NON_PROCESSABLE_SETTLEMENT_STATUS = "NON_PROCESSABLE_SETTLEMENT_STATUS"
    SOURCE_DATA_QUALITY_ISSUE = "SOURCE_DATA_QUALITY_ISSUE"


class Classification(StrEnum):
    OBSERVED = "observed"
    CALCULATED = "calculated"
    INFERRED = "inferred"


class SubjectType(StrEnum):
    SETTLEMENT = "SETTLEMENT"
    ORDER = "ORDER"


class RunState(StrEnum):
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
