import { expect, test } from '@playwright/test'

test('background keeps moving without input, responds to pointer and can be paused', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  const background = page.locator('.landing-backdrop')
  const plane = background.locator('.pc-background-plane').first()
  const parallax = background.locator('.pc-parallax').first()
  await expect(background).toHaveAttribute('aria-hidden', 'true')
  expect(await page.locator('.pc-artifact').evaluate((element) => element.getAnimations({ subtree: true }).length)).toBe(0)
  const start = await plane.evaluate((element) => getComputedStyle(element).transform)
  await expect.poll(() => plane.evaluate((element) => getComputedStyle(element).transform)).not.toBe(start)
  await page.mouse.move(10, 100)
  await expect.poll(() => background.evaluate((element) => element.style.getPropertyValue('--pointer-y'))).not.toBe('')
  const beforePointer = await parallax.evaluate((element) => getComputedStyle(element).transform)
  await page.mouse.move(1200, 700)
  await expect.poll(() => parallax.evaluate((element) => getComputedStyle(element).transform)).not.toBe(beforePointer)

  const pause = page.getByRole('button', { name: 'Pause background animation' })
  await pause.focus()
  await page.keyboard.press('Enter')
  await expect(plane).toHaveCSS('animation-play-state', 'paused')
  const paused = await plane.evaluate((element) => getComputedStyle(element).transform)
  await page.mouse.move(100, 200)
  expect(await plane.evaluate((element) => getComputedStyle(element).transform)).toBe(paused)
  await page.getByRole('button', { name: 'Resume background animation' }).click()
  await expect(plane).toHaveCSS('animation-play-state', 'running')
  await expect(page.getByRole('link', { name: 'Open workspace', exact: true })).toBeVisible()
})

test('reduced-motion visitors get a static background, including after preference changes', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const background = page.locator('.landing-backdrop')
  await expect(background).toHaveAttribute('data-motion', 'paused')
  await page.mouse.move(800, 600)
  expect(await background.evaluate((element) => element.style.getPropertyValue('--pointer-y'))).toBe('')
  await expect(page.locator('.pc-background-plane').first()).toHaveCSS('animation-play-state', 'paused')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await expect(background).toHaveAttribute('data-motion', 'running')
  await expect(page.locator('.pc-background-plane').first()).toHaveCSS('animation-play-state', 'running')
})

test('a reduced-motion visitor can explicitly enable and stop the scene', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const enable = page.getByRole('button', { name: 'Resume background animation' })
  await expect(enable).toBeVisible()
  await enable.click()
  const plane = page.locator('.pc-background-plane').first()
  await expect(page.locator('.landing-backdrop')).toHaveAttribute('data-motion', 'running')
  const initial = await plane.evaluate((element) => getComputedStyle(element).transform)
  await expect.poll(() => plane.evaluate((element) => getComputedStyle(element).transform)).not.toBe(initial)
  await page.getByRole('button', { name: 'Pause background animation' }).click()
  await expect(plane).toHaveCSS('animation-play-state', 'paused')
})

test('animated landing stays contained on desktop, tablet and narrow mobile', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  await page.locator('.pc-product-frame img').last().scrollIntoViewIfNeeded()
  await expect.poll(() => page.locator('.pc-product-frame img').evaluateAll((images) => images.every((image) => (image as HTMLImageElement).complete && (image as HTMLImageElement).naturalWidth > 0))).toBe(true)
  await page.evaluate(() => window.scrollTo(0, 0))
  for (const width of [1440, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    const proof = await page.locator('.pc-proof-object').boundingBox()
    const field = await page.locator('.pc-artifact').boundingBox()
    expect(proof!.x).toBeGreaterThanOrEqual(field!.x)
    expect(proof!.x + proof!.width).toBeLessThanOrEqual(field!.x + field!.width)
    const brand = await page.locator('.pc-nav .pc-brand').boundingBox()
    const controls = await page.locator('.pc-nav-actions').boundingBox()
    expect(brand!.x + brand!.width).toBeLessThanOrEqual(controls!.x)
    if (width === 1440 || width === 390) {
      await page.screenshot({ path: `../docs/screenshots/${width === 1440 ? 'landing' : 'landing-mobile'}.png`, fullPage: true, animations: 'disabled' })
    }
  }
})
